name: Waka Readme

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SHOW_TIME: false
          TIME_RANGE: all_time
          CODE_LANG: rust
          LANG_COUNT: 10
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          IGNORED_LANGUAGES: Vue.js YAML YML TOML JSON Markdown HTML CSS SCSS XML
